name: Merge On Issue Close

description: Merges the pull request when the associated issue has been close.

inputs:
  github-token:
    description: Your Github token, it's already available to your Github action.
    required: false
    default: ${{ github.token }}
  tester:
    description: The person to assign the linked issue for testing.
    required: true

runs:
  using: node16
  main: 'dist/index.js'